/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.oytu.darwinismo;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class TelaAdd extends javax.swing.JFrame {

    /** Creates new form TelaAdd */
    public TelaAdd() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x_lbl = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        x_lbl1 = new javax.swing.JLabel();
        tf_volume = new javax.swing.JTextField();
        x_lbl2 = new javax.swing.JLabel();
        tf_valor = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x_lbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        x_lbl.setForeground(new java.awt.Color(51, 51, 51));
        x_lbl.setText("Nome:");
        getContentPane().add(x_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 270, -1));

        x_lbl1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        x_lbl1.setForeground(new java.awt.Color(51, 51, 51));
        x_lbl1.setText("Volume:");
        getContentPane().add(x_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(tf_volume, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 270, -1));

        x_lbl2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        x_lbl2.setForeground(new java.awt.Color(51, 51, 51));
        x_lbl2.setText("Valor:");
        getContentPane().add(x_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(tf_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 270, -1));

        btn_salvar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        final String PATH = "D:/save.txt";
        /**
         * Método que salva o item ao clicar no botao,
         * ele carrega os itens salvos e add no array para
         * depois serializalos para salvar novamente
         */
        String nome = tf_nome.getText().toString();
        Double volume = 0.0;
        Double valor = 0.0;
        try {
            volume = Double.parseDouble(tf_volume.getText().toString());
            valor = Double.parseDouble(tf_valor.getText().toString());
        } catch (NumberFormatException e) {

        }
        if(nome.equals("")|| volume == 0||valor == 0){
            JOptionPane.showMessageDialog(null, "Campo vazio ou inválido");
            return;
        }
        //tá no g i tou
        
        Save s = new Save();
        ArrayList<Produto> itens;
        if (!s.exists(PATH)) {   //se nao existir ele cria
            itens = new ArrayList<>();
            itens.add(new Produto(nome,volume,valor));
            try {
                s.salvar(PATH, itens);
            } catch (IOException ex) {
                Logger.getLogger(TelaAdd.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            itens = (ArrayList<Produto>) s.recordar(); //se existir ele recorda
            itens.add(new Produto(nome,volume,valor));
            try {
                s.salvar(PATH, itens);
            } catch (IOException ex) {
                Logger.getLogger(TelaAdd.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JOptionPane.showMessageDialog(null,"Salvo");
        
        tf_nome.setText("");
        tf_volume.setText("");
        tf_valor.setText("");
        
//        for (int i = 0; i < itens.size(); i++) {
//                System.out.println(" " + itens.get(i).getNome());
//            }
    }//GEN-LAST:event_btn_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showTelaAdd() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvar;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_valor;
    private javax.swing.JTextField tf_volume;
    private javax.swing.JLabel x_lbl;
    private javax.swing.JLabel x_lbl1;
    private javax.swing.JLabel x_lbl2;
    // End of variables declaration//GEN-END:variables


}
