/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oytu.darwinismo;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jfree.chart.ui.ApplicationFrame;
import org.jfree.chart.ui.UIUtils;

/**
 *
 * @author Vinicius
 */
public class TelaGenetico extends javax.swing.JFrame{
    final String PATH = "D:/save.txt";
    ArrayList<Produto> produtos;
    /**
     * Creates new form TelaGenetico
     */
    public TelaGenetico() {
        initComponents();
        this.produtos = this.reloadData();
        this.showData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        x_lbl = new javax.swing.JLabel();
        x_lbl1 = new javax.swing.JLabel();
        x_lbl2 = new javax.swing.JLabel();
        x_lbl3 = new javax.swing.JLabel();
        j_slider_gerassaum = new javax.swing.JSlider();
        j_slider_mutassaum = new javax.swing.JSlider();
        j_slider_populassaum = new javax.swing.JSlider();
        tf_valorMaximo = new javax.swing.JTextField();
        lbl_gerassaum = new javax.swing.JLabel();
        lbl_mutassaum = new javax.swing.JLabel();
        lbl_populassaum = new javax.swing.JLabel();
        btn_aplicar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        j_menu_add = new javax.swing.JMenu();
        j_submenu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(400, 320));
        setMinimumSize(new java.awt.Dimension(400, 320));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x_lbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        x_lbl.setText("Valor Máximo");
        getContentPane().add(x_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        x_lbl1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        x_lbl1.setText("Taxa de Mutação");
        getContentPane().add(x_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        x_lbl2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        x_lbl2.setText("População");
        getContentPane().add(x_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        x_lbl3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        x_lbl3.setText("Gerações");
        getContentPane().add(x_lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        j_slider_gerassaum.setToolTipText("");
        j_slider_gerassaum.setValue(0);
        j_slider_gerassaum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                j_slider_gerassaumStateChanged(evt);
            }
        });
        getContentPane().add(j_slider_gerassaum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        j_slider_mutassaum.setValue(0);
        j_slider_mutassaum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                j_slider_mutassaumStateChanged(evt);
            }
        });
        getContentPane().add(j_slider_mutassaum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        j_slider_populassaum.setValue(0);
        j_slider_populassaum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                j_slider_populassaumStateChanged(evt);
            }
        });
        getContentPane().add(j_slider_populassaum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));
        getContentPane().add(tf_valorMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 180, -1));

        lbl_gerassaum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_gerassaum.setText("0");
        getContentPane().add(lbl_gerassaum, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        lbl_mutassaum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_mutassaum.setText("0");
        getContentPane().add(lbl_mutassaum, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        lbl_populassaum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_populassaum.setText("0");
        getContentPane().add(lbl_populassaum, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        btn_aplicar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_aplicar.setText("Aplicar");
        btn_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        j_menu_add.setText("Opções");
        j_menu_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_menu_addActionPerformed(evt);
            }
        });

        j_submenu.setText("Add Item");
        j_submenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_submenuActionPerformed(evt);
            }
        });
        j_menu_add.add(j_submenu);

        jMenuBar1.add(j_menu_add);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_menu_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_menu_addActionPerformed
        //xxxxx
    }//GEN-LAST:event_j_menu_addActionPerformed

    private void j_submenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_submenuActionPerformed
       TelaAdd add = new TelaAdd();
       add.setVisible(true);
       //preciso verificar se a tela ficou invisivel para recarregar os itens salvos
       new Thread(){
           @Override
           public void run(){
               while(true){
                   if(!add.isVisible()){
                       produtos = reloadData();
                       showData();
                       break;
                   }
                   try {
                       Thread.sleep(400);
                   } catch (InterruptedException ex) {
                       Logger.getLogger(TelaGenetico.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
           }
       }.start();
    }//GEN-LAST:event_j_submenuActionPerformed

    private void j_slider_mutassaumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_j_slider_mutassaumStateChanged
        lbl_mutassaum.setText(j_slider_mutassaum.getValue()+"");
    }//GEN-LAST:event_j_slider_mutassaumStateChanged

    private void j_slider_populassaumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_j_slider_populassaumStateChanged
        lbl_populassaum.setText(j_slider_populassaum.getValue()+"");
    }//GEN-LAST:event_j_slider_populassaumStateChanged

    private void j_slider_gerassaumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_j_slider_gerassaumStateChanged
        lbl_gerassaum.setText(j_slider_gerassaum.getValue()+"");
    }//GEN-LAST:event_j_slider_gerassaumStateChanged

    private void btn_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aplicarActionPerformed
        //definindo e verificandos
        double mutassaum = Double.valueOf( j_slider_mutassaum.getValue());
        int populassaum = j_slider_populassaum.getValue();
        int gerassaum = j_slider_gerassaum.getValue();
        double valorMaximo = 0.0;
        if(!tf_valorMaximo.getText().equals(""))
            valorMaximo = Double.parseDouble(tf_valorMaximo.getText());
        else{
            JOptionPane.showMessageDialog(null, "Campo 'Valor Maximo' vazio");
            return;}
        if(mutassaum == 0 || populassaum == 0 || gerassaum == 0 || valorMaximo == 0){
            JOptionPane.showMessageDialog(null, "Os campos não foram preenchidos corretamente");
            return ;
        }
        
        ///--------------
        List<Produto> listaProdutos = new ArrayList<>();
        listaProdutos.add(new Produto("Geladeira Dako", 0.751, 999.90));
        listaProdutos.add(new Produto("Iphone 6", 0.000089, 2911.12));
        listaProdutos.add(new Produto("TV 55'", 0.400, 4346.99));
        listaProdutos.add(new Produto("TV 50'", 0.290, 3999.90));
        listaProdutos.add(new Produto("TV 42'", 0.200, 2999.00));
        listaProdutos.add(new Produto("Notebook Dell", 0.00350, 2499.90));
        listaProdutos.add(new Produto("Ventilador Panasonic", 0.496, 199.90));
        listaProdutos.add(new Produto("Microondas Electrolux", 0.0424, 308.66));
        listaProdutos.add(new Produto("Microondas LG", 0.0544, 429.90));
        listaProdutos.add(new Produto("Microondas Panasonic", 0.0319, 299.29));
        listaProdutos.add(new Produto("Geladeira Brastemp", 0.635, 849.00));
        listaProdutos.add(new Produto("Geladeira Consul", 0.870, 1199.89));
        listaProdutos.add(new Produto("Notebook Lenovo", 0.498, 1999.90));
        listaProdutos.add(new Produto("Notebook Asus", 0.527, 3999.00));
        //----------------
        
        //definições do algoritimo genético
        List espacos = new ArrayList<>();
        List valores = new ArrayList<>();
        List nomes = new ArrayList<>();
        
         for(Produto produto: this.produtos){
        //for(Produto produto: listaProdutos){
            espacos.add(produto.getEspaco());
            valores.add(produto.getValor());
            nomes.add(produto.getNome());
        }
        
        AlgoritmoGenetico ag = new AlgoritmoGenetico(populassaum);
        List resultado = ag.resolver(mutassaum, gerassaum, espacos, valores, valorMaximo);
        List<Individuo> gera = ag.getGeracoes();
        
        TimesSeriesChart demo = new TimesSeriesChart("Algoritmo Genético", gera);
        demo.pack();
        UIUtils.centerFrameOnScreen(demo);
        demo.setVisible(true);
       
//        for (int i = 0; i < gera.size(); i++) {
//            System.out.println("G: "+gera.get(i).getGeracao()+"| Avaliasao "+gera.get(i).getNotaAvaliacao());
//        }
    }//GEN-LAST:event_btn_aplicarActionPerformed

    private ArrayList<Produto>  reloadData(){
        Save s = new Save();
        if (s.exists(PATH))
            return (ArrayList<Produto>) s.recordar();
        return new ArrayList<Produto>();
    }
    
    private void showData(){
        System.out.println("------------------");
        for (int i = 0; i < this.produtos.size(); i++) {
            System.out.println("Nome: "+this.produtos.get(i).getNome()+" | volume: "+this.produtos.get(i).getEspaco());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenetico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aplicar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu j_menu_add;
    private javax.swing.JSlider j_slider_gerassaum;
    private javax.swing.JSlider j_slider_mutassaum;
    private javax.swing.JSlider j_slider_populassaum;
    private javax.swing.JMenuItem j_submenu;
    private javax.swing.JLabel lbl_gerassaum;
    private javax.swing.JLabel lbl_mutassaum;
    private javax.swing.JLabel lbl_populassaum;
    private javax.swing.JTextField tf_valorMaximo;
    private javax.swing.JLabel x_lbl;
    private javax.swing.JLabel x_lbl1;
    private javax.swing.JLabel x_lbl2;
    private javax.swing.JLabel x_lbl3;
    // End of variables declaration//GEN-END:variables

}
